help alphabet: user.help_alphabet(user.get_alphabet())
help all: user.help_context()
help active: user.help_context_enabled()
help refresh: user.help_refresh()
help next: user.help_next()
help previous: user.help_previous()
help context <user.help_contexts>: user.help_selected_context(user.help_contexts)
help <user.help_context_index>: user.help_select_index(help_context_index)
help return: user.help_return()
help close: user.help_hide()

