help alphabet: user.help_alphabet(user.get_alphabet())
help symbols: user.help_symbol_key_words(user.get_symbol_key_words())
help context$: user.help_context()
help active$: user.help_context_enabled()
help search <user.text>$: user.help_search(text)
help context {user.help_contexts}$: user.help_selected_context(help_contexts)
help help: user.help_search("help")
