zoom in: edit.zoom_in()
zoom out: edit.zoom_out()
zoom reset: edit.zoom_reset()
scroll up: edit.page_up()
scroll down: edit.page_down()
copy (that | it): edit.copy()
cut (that | it): edit.cut()
paste (that | it): edit.paste()
undo (that | it): edit.undo()
redo (that | it): edit.redo()
paste match: edit.paste_match_style()
file save: edit.save()
(pad | padding): user.insert_between(" ", " ")
slap: edit.line_insert_down()
