new window: app.window_open()
next window: app.window_next()
last window: app.window_previous()
close window: app.window_close()
focus <user.actions.switcher.running_applications>: user.actions.switcher.focus(user.actions.switcher.running_applications)
