new window: app.window_open()
next window: app.window_next()
last window: app.window_previous()
close window: app.window_close()
#focus <user.running_applications>: user.switcher_focus(running_applications)
focus <user.text>: user.switcher_focus(text)
list running: user.switcher_list_running()
hide running: user.switcher_hide_running()
