import os
from .data_classes.windows_application import windows_application
from talon import app

if app.platform == "windows":
    explorer_path = str(os.path.expandvars(os.path.join("%WINDIR%", "explorer.exe")))
    settings_path = str(os.path.expandvars(os.path.join("%WINDIR%", "ImmersiveControlPanel", "SystemSettings.exe")))
    windows_speech_recognition = str(os.path.expandvars(os.path.join("%WINDIR%", "speech", "Common", "sapisvr.exe")))
    mmc = str(os.path.expandvars(os.path.join("%WINDIR%", "system32", "mmc.exe"))) 

    windows_applications = [
        windows_application(display_name="Control Panel", 
                        unique_identifier="Microsoft.Windows.ControlPanel",
                        executable_path=explorer_path,
                        executable_name="explorer.exe"),
        windows_application(display_name="File Explorer", 
                        unique_identifier="Microsoft.Windows.Explorer", 
                        executable_path=explorer_path,
                        executable_name="explorer.exe"),  
        windows_application(display_name="Run", 
                        unique_identifier="Microsoft.Windows.Shell.RunDialog", 
                        executable_path=explorer_path,
                        executable_name="explorer.exe"),       
        windows_application(display_name="Settings", 
                        unique_identifier="windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel", 
                        executable_path=settings_path,
                        executable_name="SystemSettings.exe"), 
        windows_application(display_name="This PC", 
                        unique_identifier="Microsoft.Windows.Computer",
                        executable_path=explorer_path,
                        executable_name="explorer.exe"),
        windows_application(display_name="Windows Speech Recognition", 
                        unique_identifier="Microsoft.AutoGenerated.{DAA168DE-4306-C8BC-8C11-B596240BDDED}", 
                        executable_path=windows_speech_recognition,
                        executable_name="sapisvr.exe"),                         
    ]

    windows_application_dict = {}
    for application in windows_applications:
        unique_identifier = application.unique_identifier
        windows_application_dict[unique_identifier.lower()] = application
else:
    mmc = "INVALID"
    windows_application_dict = {}
    explorer_path = None

def get_known_windows_application(uuid) -> windows_application:
    if uuid.lower() in windows_application_dict:
        return windows_application_dict[uuid.lower()]
    else:
        return None