^microphone show$: user.microphone_selection_toggle()
^microphone close$: user.microphone_selection_hide()
^microphone pick <number_small>$: user.microphone_select(number_small)
^speaker show$: user.speaker_selection_toggle()
^speaker pick <number_small>$: user.speaker_select(number_small)
toggle (conference|teams|discord|zoom|meat): user.microphone_toggle_video_conference()