desk <number_small>: user.desktop(number_small)
desk (next|right): user.desktop_next()
desk (last|left): user.desktop_last()
desk show: user.desktop_show()
window move desk <number>: user.window_move_desktop(number)
window move desk left: user.window_move_desktop_left()
window move desk right: user.window_move_desktop_right()
