(rejection|reject) history: user.rejection_history_toggle()
copy (lest|last) (reject|rejection): user.rejection_copy_last()
[move] reject [category] [good] one: user.rejection_move_last(1)
[move] reject [category] [good] two: user.rejection_move_last(2)
[move] reject [category] bad [three]: user.rejection_move_last(3)
move reject <number_small> category one: user.rejection_move(1, number_small)
move reject <number_small> category two: user.rejection_move(2, number_small)