phones <user.homophones_canonical>: user.homophones_show(homophones_canonical)
phones: user.homophones_show_selection()
phones force <user.homophones_canonical>: user.homophones_force_show(homophones_canonical)
phones force: user.homophones_force_show_selection()
phones hide: user.homophones_hide()